routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
}); 
Route::get('/login', function () {
    return view('auth.login');
});


Route::post('/sesion', 'controladorLogin@login');
Route::get('/prueba', 'controladorLogin@prueba');
Route::get('/logout', 'controladorLogin@logout');
/*==============================================*/
/*==============================================*/

#SEGURIDAD DEL MIDDLEWARE PARA LA URL ARCHIVOS QUE LO DOMINAN: /En: MIDDLEWARE SECURITY FOR THE URL DOMAIN FILE: 
#middlewareSesion.php/kernel.php/controladorLogin /En: middlewareSesion.php / kernel.php / controllerLogin

/*=================================================*/
             #RUTAS PARA LOS USUARIOS LOGUEADOS
/*=================================================*/

if(!isset($_SESSION)) 
{ 
    session_start(); 
} 

Route::group(['middleware' => 'sesion'], function () {
	Route::get('/home', 'homeController@index');
});

Route::group(['middleware' => 'analista'], function () {
	Route::get('/proveedores', 'controladorProveedores@index');
	Route::resource('proveedores', 'controladorProveedores');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-provee', 'controladorProveedores@exportProvee');

	# ANEXO T2 = concurso
	Route::get('/concurso', 'controladorConcurso@index');
	Route::resource('concurso', 'controladorConcurso');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-concu', 'controladorConcurso@exportConcurso');

	# ANEXO T2-1 = directa
	Route::get('/directa', 'controladorDirecta@index');
	Route::resource('directa', 'controladorDirecta');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-directa', 'controladorDirecta@exportDirecta');

	# ANEXO T2-2 = confiscacion
	Route::get('/confiscacion', 'controladorConfiscacion@index');
	Route::resource('confiscacion', 'controladorConfiscacion');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-confiscacion', 'controladorConfiscacion@exportConfis');

	# ANEXO T2-3 = dacion
	Route::get('/dacion', 'controladorDacion@index');
	Route::resource('dacion', 'controladorDacion');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-dacion', 'controladorDacion@exportDacion');

	# ANEXO T2-4 = donacion
	Route::get('/donacion', 'controladorDonacion@index');
	Route::resource('donacion', 'controladorDonacion');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-donacion', 'controladorDonacion@exportDonacion');

	# ANEXO T2-5 = expropiacion
	Route::get('/expropiacion', 'controladorExpropiacion@index');
	Route::resource('expropiacion', 'controladorExpropiacion');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-expro', 'controladorExpropiacion@exportExpro');

	# ANEXO T2-6 = permuta
	Route::get('/permuta', 'controladorPermuta@index');
	Route::resource('permuta', 'controladorPermuta');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-permuta', 'controladorPermuta@exportPermuta');

	# ANEXO T2-7 = transferencia
	Route::get('/transferencia', 'controladorTransferencia@index');
	Route::resource('transferencia', 'controladorTransferencia');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-transfe', 'controladorTransferencia@exportTransfe');

	# ANEXO T2-8 = adjudicacion
	Route::get('/adjudicacion', 'controladorAdjudicacion@index');
	Route::resource('adjudicacion', 'controladorAdjudicacion');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-adjud', 'controladorAdjudicacion@exportAdjud');

	# ANEXO T3 = seguros
	Route::get('/seguros', 'controladorSeguros@index');
	Route::resource('seguros', 'controladorSeguros');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-seguro', 'controladorSeguros@exportSeguro');

	# ANEXO T4 = responsables
	Route::get('/responsables', 'controladorResponsables@index');
	Route::resource('responsables', 'controladorResponsables');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-respon', 'controladorResponsables@exportRespon');


	# ANEXO T5 = Marcas
	Route::resource('marcas', 'controladorAddMarca');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-marcas', 'controladorAddMarca@exportMarcas');

	# ANEXO T6 = Modelos
	Route::get('/modelos', 'controladorAddModelos@index');
	Route::resource('modelos', 'controladorAddModelos');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-modelos', 'controladorAddModelos@exportModelos');

	# ANEXO T7 = Componentes
	Route::get('/componentes', 'controladorComponentes@index');
	Route::resource('componentes', 'controladorComponentes');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-compo', 'controladorComponentes@exportCompo');

	# ANEXO T8 = Bienes
	Route::get('/bienes', 'controladorBienes@index');
	Route::resource('bienes', 'controladorBienes');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-bienes', 'controladorBienes@exportBienes');

	# ANEXO T9 = Equipo de Transporte
	Route::get('/transporte', 'controladorEqtransporte@index');
	Route::resource('transporte', 'controladorEqtransporte');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-trans', 'controladorEqtransporte@exportTranspo');

	# ANEXO T10 = Semovientes
	Route::get('/semovientes', 'controladorSemovientes@index');
	Route::resource('semovientes', 'controladorSemovientes');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-semo', 'controladorSemovientes@exportSemo');

	# ANEXO T11 = Datos de los Bienes
	Route::get('/datosbienes', 'controladorDatosbienes@index');
	Route::resource('datosbienes', 'controladorDatosbienes');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-muebles', 'controladorDatosbienes@exportMuebles');

	# ANEXO T12 = Datos de los Inmuebles
	Route::get('/datosinmuebles', 'controladorInmuebles@index');
	Route::resource('datosinmuebles', 'controladorInmuebles');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-inmuebles', 'controladorInmuebles@exportInmuebles');

	# SELECT DINAMICOS
			/*===Registrar Marcas y Modelos Anexos T===*/
	Route::get('dropdown/{id}','controladorBienes@getBienes');

	/*============Modificar Marcas y Modelos Anexos T==============*/
	Route::get('dropdown2/{id}','controladorBienes@getBienesmodif');

			/*===Registrar dependencia y responsable Anexos  T -Bienes===*/
	Route::get('downsede/{id}','controladorBienes@depenResponsable');

	/*============Registrar dependencia y responsable Anexos T -Transporte==============*/
	Route::get('downtran/{id}','controladorEqtransporte@depenResponsable');

	/*============Registrar dependencia y responsable Anexos T -Semovientes==============*/
	Route::get('downsemo/{id}','controladorSemovientes@depenResponsemo');

	/*============Registrar dependencia y responsable Anexos T -Inmuebles==============*/
	Route::get('downinmu/{id}','controladorInmuebles@depenResponsableIn');

	/*=================================================*/
				  # ANEXOS S
				  # ANEXO S1 = Datos Básicos
	/*=================================================*/

	Route::get('/basicos', 'controladorS1@index');
	Route::resource('basicos', 'controladorS1');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-basicos', 'controladorS1@exporBasicos');

	# ANEXO S2 = Datos Máxima Autoridad
	Route::get('/maxima', 'controladorS2@index');
	Route::resource('maxima', 'controladorS2');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-maxima', 'controladorS2@exportMaxima');

	# ANEXO S3 = Datos del Responsable Patrimonial
	Route::get('/patrimonial', 'controladorS3@index');
	Route::resource('patrimonial', 'controladorS3');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-patrimonial', 'controladorS3@exportPatrimonial');

	# ANEXO S4 = Datos de la sede
	Route::get('/sedes', 'controladorS4@index');
	Route::resource('sedes', 'controladorS4');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-sedes', 'controladorS4@exportSedes');

	# ANEXO S5 = Datos de las Unidades Administrativas
	Route::get('/unidades', 'controladorS5@index');
	Route::resource('unidades', 'controladorS5');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-unidades', 'controladorS5@exportUnidades');

	# ANEXO S6 = Datos de las Unidades Administrativas
	Route::get('/ubicacion', 'controladorS6@index');
	Route::resource('ubicacion', 'controladorS6');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-ubicacion', 'controladorS6@exportUbicacion');


	/*------------------------------  // -------------------------*/

	# SELECT LOCALIZACIÓN Y SELECT CODIGO DE PARROQUIA PARA CUANDO SELECCIONE INTERNACIONAL SE COLOQUE 99 EN CASO CONTRARIO TRAIGA LAS OPCIONES DEL OPTION(SELECT)

	/*------------- Vista Inmuebles pertenece al controlador inmuebles-------------*/

	/*== Ruta Paises ==*/
	Route::get('paisIn/{id}', 'controladorInmuebles@paisInmu');
	/*== Ruta Parroquias ==*/
	Route::get('parroIn/{id}', 'controladorInmuebles@parroInmu');
	/*== Ruta Ciudad ==*/
	Route::get('ciudadIn/{id}', 'controladorInmuebles@ciudadInmu');

	/* Modificar Inmuebles pertenece al controlador inmuebles*/
	/*== Ruta Paises ==*/
	Route::get('paisModi/{id}', 'controladorInmuebles@modifiPais');
	/*== Ruta Parroquias ==*/
	Route::get('parroModi/{id}', 'controladorInmuebles@modifiParro');
	/*== Ruta Ciudad ==*/
	Route::get('ciudadModi/{id}', 'controladorInmuebles@modifiCiudad');

	/*------------------------------  // -------------------------*/

	/*------------- Vista Datos de las Sedes pertenece al controladorS4 -------------*/

	/*== Ruta Paises S4 ==*/

resources/views/layouts/ModificarAnexosT/modificarAdjudicacion.blade.php
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Modificar Adjudicación</title>
		 <link href="{{ asset('css/app.css') }}" rel="stylesheet">
	     <link href="{{ asset('css/appstilo.css') }}" rel="stylesheet">  
	     <link href="{{ asset('css/general.css') }}" rel="stylesheet">  
	     <link href="{{ asset('css/tablas.css') }}" rel="stylesheet">  
	     <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
	     <link href="{{ asset('css/bootstrap-datepicker.min.css') }}" rel="stylesheet" type="text/css">
	     <link href="{{ asset('img/bandera.png') }}" rel="icon">
	</head>
<body>


<div class="container" id="sha">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="panel">
		            <img src="{{URL::asset('/img/cintillo.jpg')}}" id="banner" alt="Cintillo Web">
		                <div class="panel-heading text-center"><h5><b>MODIFICAR ADJUDICACIÓN <i class="fa fa-pencil-square-o" aria-hidden="true"></i></b></h5></div>
			    </div>
			</div>

		    <div class="row">
			    <div class="col-md-12 text-center">
			        <h4>Modificar Registro <b id="colorInstruccion">N°# {{$form_t28->id}}</b></h4>
			    </div>
			</div>

	    <hr>

			<div class="row">
	        	<div class="col-md-12 desvanecer">
	         	@if(session()->has('msj'))
	              <center><div  class="col-md-12  alert alert-success" role="alert">{{session('msj')}}</div></center>
	                 @endif

	                 @if(session()->has('errormsj'))
	              <center><div  class="col-md-12  alert alert-danger" role="alert">{{session('errormsj')}}</div></center>
	            @endif
	        	</div>
	     	</div>
			
		<form role="form" method="POST" action="{{route('adjudicacion.update', $form_t28->id)}}">
	       	  <input type="hidden" name="_method" value="PUT">
	            {{ csrf_field() }}

			
			<div class="row separar40 ">
				<div class="col-md-12">
					<div class="col-md-4">
						<label for="codOt2_8">Código de Origen</label>
						@if($form_t28->codOt2_8 == '')
						 <input type="text" class="form-control" name="codOt2_8" id="codOt2_8" value="I-1" maxlength="12">
						@else
						 <input type="text" class="form-control" name="codOt2_8" id="codOt2_8" value="{{$form_t28->codOt2_8}}" maxlength="12">
						@endif
					</div>
				
		    

					<div class="col-md-4 form-group">
		           	  <label for="codAdq"><b class="requiredV">*</b>Código de Adquisición</label>
		                <select name="codAdq" id="codAdq" class="form-control">
		                    <option value="{{$form_t28->selectAdjudicacion->id}}">{{$form_t28->selectAdjudicacion->opcion}}</option>
		                  @foreach($infoSelect as $form)
		                  	@if($form->id != $form_t28->selectAdjudicacion->id)
		                    <option value="{{$form->id}}">{{$form->opcion}}</option> 
		                    @endif
		                  @endforeach
		                </select>
					</div>

					<div class="col-md-4">
						<label for="nomProan">Nombre del Propietario Anterior</label>
						@if($form_t28->nomProan == '1')
						 <input type="text" class="form-control" name="nomProan" id="nomProan" value="xxx" maxlength="100">
						@else
						 <input type="text" class="form-control" name="nomProan" id="nomProan" value="{{$form_t28->nomProan}}" maxlength="100">
						@endif
					</div>
				</div>
			</div>
			
			<div class="row separar40">
				<div class="col-md-12">
					<div class="col-md-4">
						<label for="nomBen">Nombre del Beneficiario</label>
						@if($form_t28->nomBen == '1')
						 <input type="text" class="form-control" name="nomBen" id="nomBen" value="noaplica" maxlength="100">
						@else
						 <input type="text" class="form-control" name="nomBen" id="nomBen" value="{{$form_t28->nomBen}}" maxlength="100">
						@endif
					</div>
		
				    <div class="col-md-4">
						<label for="nomAuto">Nombre de la Autoridad</label>
						@if($form_t28->nomAuto == '1')
						 <input type="text" class="form-control" name="nomAuto" id="nomAuto" value="xxx" maxlength="100">
						@else
						 <input type="text" class="form-control" name="nomAuto" id="nomAuto" value="{{$form_t28->nomAuto}}" maxlength="100">
						@endif
				    </div>

				    <div class="col-md-4">
						<label for="nomRegn">Número de Sentencia o Acto Administrativo</label>
						@if($form_t28->numSeAdm == '0')
						 <input type="text" class="form-control" name="numSeAdm" id="numSeAdm" value="xxx" maxlength="30">
						@else
						 <input type="text" class="form-control" name="numSeAdm" id="numSeAdm" value="{{$form_t28->numSeAdm}}" maxlength="30">
						@endif
				    </div>
			    </div>
			</div>

			<div class="row separar40">
				<div class="col-md-12">
				    <div class="col-md-4">
						<label for="nomRegn">Nombre del Registro o Notaría</label>
						@if($form_t28->nomRegn == '1')
					    <input type="text" class="form-control" name="nomRegn" id="nomRegn" value="xxx" maxlength="100">
						@else
						<input type="text" class="form-control" name="nomRegn" id="nomRegn" value="{{$form_t28->nomRegn}}" maxlength="100">
						@endif
					</div>	

					<div class="col-md-4">
						<label for="tomo">Tomo</label>
						@if($form_t28->tomo == '1')
						<input type="text" class="form-control" name="tomo" id="tomo" value="xxx" maxlength="20">
						@else
					    <input type="text" class="form-control" name="tomo" id="tomo" value="{{$form_t28->tomo}}" maxlength="20">
						@endif
					</div>

					<div class="col-md-4">
						<label for="folio">Folio</label>
						@if($form_t28->folio == '0')
						 <input type="text" class="form-control" name="folio" id="folio" value="99" maxlength="6" onkeypress="return soloNum(event)">
						@else
						 <input type="text" class="form-control" name="folio" id="folio" value="{{$form_t28->folio}}" maxlength="6" onkeypress="return soloNum(event)">
						@endif
				    </div>
				</div>
			</div>
		    
		
			<div class="row separar40">	  
				<div class="col-md-12">
					 <div class="col-md-4">
						  <label for="feSeAdm">Fecha de Registro</label>
						@if($form_t28->feSeAdm == '1111-11-11')
						  <input type="text" class="form-control calendario" name="feSeAdm" id="feSeAdm" value="11111111">
						@else
						  <input type="text" class="form-control calendario" name="feSeAdm" id="feSeAdm" value="{{$form_t28->feSeAdm}}">
						@endif
					</div>

					<div class="col-md-4">
						  <label for="feReg">Fecha de Registro</label>
						@if($form_t28->feReg == '1111-11-11')
						  <input type="text" class="form-control calendario" name="feReg" id="feReg" value="11111111">
						@else
						  <input type="text" class="form-control calendario" name="feReg" id="feReg" value="{{$form_t28->feReg}}">
						@endif
					</div>
				</div>
			</div>

			
			<div class="row">
	              <div class="col-md-12 form-group"><br>
	                <center><button type="submit" class="btn btn-sm btn-info" name="#"><i class="fa fa-check-square-o" aria-hidden="true"></i> <b>Modificar</b></button>
	                 <a href="{{ url('/regAdjudicacion') }}"  class="btn btn-sm btn-danger" ><i class="fa fa-reply " aria-hidden="true" title="Regresar"></i> <b>Regresar</b></a></center>  
	              </div>
	        </div>
        </div>
	</div>
</div>
</form>
</body>
</html>

 	<script src="{{ asset('js/jquery-3.1.0.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/moment.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('js/validate.js') }}"></script>
    <script src="{{ asset('js/validateGeneral.js') }}"></script>
    <script src="{{ asset('js/validateDatepicker.js') }}"></script>

resources/views/layouts/ModificarAnexosT/modificarComponentes.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Modificar Proveedores</title>

     <link href="{{ asset('css/app.css') }}" rel="stylesheet">
     <link href="{{ asset('css/appstilo.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/general.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/tablas.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">

  </head>
<body>

<div class="container" id="sha">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="panel">
                     <img src="{{URL::asset('/img/cintillo.jpg')}}" id="banner" alt="Cintillo Web">
                   <div class="panel-heading text-center"><h5><b>MODIFICAR COMPONENTES <i class="fa fa-pencil-square-o" aria-hidden="true"></i></b></h5></div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-center">
                    <h4>Modificar Registro <b id="colorInstruccion">N°# {{$form_t7->id}}</b></h4>
                </div>
            </div>
            
        <hr>

            <div class="row">
                <div class="col-md-12 desvanecer">
                  @if(session()->has('msj'))
                      <center><div  class="col-md-12  alert alert-success" role="alert">{{session('msj')}}</div></center>
                         @endif

                         @if(session()->has('errormsj'))
                      <center><div  class="col-md-12  alert alert-danger" role="alert">{{session('errormsj')}}</div></center>
                  @endif
                </div>
            </div>

    <form role="form" method="POST" action="{{route('componentes.update', $form_t7->id)}}" id="formValidaT7" name="formValidaT7">
        <input type="hidden" name="_method" value="PUT">
           {{ csrf_field() }}

            <div class="row separar">
                <div class="col-md-12">
                    <div class="col-md-4">
                       <label for="codigo"><b class="requiredV">*</b>Código</label>
                          <input type="text" class="form-control" name="codigo" id="codigo" value="{{$form_t7->codigo}}"  placeholder="Introduzca nombres" maxlength="10"> 
                    </div>
               
                    <div class="col-md-4">
                       <label for="denComponente"><b class="requiredV">*</b>Denominación del Componente</label>   
                          <input type="text" class="form-control" name="denComponente" id="denComponente" value="{{$form_t7->denComponente}}"  placeholder="Introduzca nombres" maxlength="100" autofocus> 
                    </div>
              
                    <div class="col-md-4">
                       <label for="codBienMueble"><b class="requiredV">*</b>Código del Bien mueble</label>   
                          <input type="text" class="form-control" name="codBienMueble" id="codBienMueble" value="{{$form_t7->codBienMueble}}"  placeholder="Introduzca nombres" maxlength="10" autofocus> 
                    </div>
                </div>
            </div>
          
              <div class="row">
                  <div class="col-md-12 form-group"><br>
                    <center><button type="submit" class="btn btn-sm btn-info" name="#"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> <b>Modificar</b></button>
                     <a href="{{ url('/regComponentes') }}"  class="btn btn-sm btn-danger" ><i class="fa fa-reply " aria-hidden="true" title="Regresar"></i> <b>Regresar</b></a></center>  
                  </div>
              </div>
        </div>
    </div>
</div>
</form>
</body>
</html>
    <script src="{{ asset('js/jquery-3.1.0.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/moment.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('js/validate.js') }}"></script>
    <script src="{{ asset('js/jquery.validate.js') }}"></script>
    <script src="{{ asset('js/validateGeneral.js') }}"></script>

resources/views/layouts/ModificarAnexosT/modificarMarcas.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Modificar Marcas</title>

     <link href="{{ asset('css/app.css') }}" rel="stylesheet">
     <link href="{{ asset('css/appstilo.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/general.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/tablas.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">

  </head>
<body>

<div class="container" id="sha">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="panel">
                     <img src="{{URL::asset('/img/cintillo.jpg')}}" id="banner" alt="Cintillo Web">
                   <div class="panel-heading text-center"><h5><b>MODIFICAR MARCAS <i class="fa fa-pencil-square-o" aria-hidden="true"></i></b></h5></div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-center">
                    <h4>Modificar Registro <b id="colorInstruccion">N°# {{$form_t5->id}}</b></h4>
                </div>
            </div>
            
          <hr>

            <div class="row">
                <div class="col-md-12 desvanecer">
                  @if(session()->has('msj'))
                      <center><div  class="col-md-12  alert alert-success" role="alert">{{session('msj')}}</div></center>
                         @endif

                         @if(session()->has('errormsj'))
                      <center><div  class="col-md-12  alert alert-danger" role="alert">{{session('errormsj')}}</div></center>
                  @endif
                </div>
            </div>

    <form role="form" method="POST" action="{{route('marcas.update', $form_t5->id)}}" id="formValidaAdd5" name="formValidaAdd5">
        <input type="hidden" name="_method" value="PUT">
           {{ csrf_field() }}

            <div class="row separar">
                <div class="col-md-12">
                    <div class="col-md-4">
                       <label for="denComar">Denominación de la Marca</label>
                          <input type="text" class="form-control" name="denComar" id="denComar" value="{{$form_t5->denComar}}"  placeholder="Introduzca nombres" maxlength="100" disabled> 
                    </div>
               
                    <div class="col-md-4">
                       <label for="codMarca"><b class="requiredV">*</b>Código de la Marca</label> 
                          <input type="text" class="form-control" name="codMarca" id="codMarca" value="{{$form_t5->codMarca}}" maxlength="10">
                    </div>

                    <div class="col-md-4">
                       <label for="nomFabri"><b class="requiredV">*</b>Nombre del Fabricante </label> 
                          <input type="text" class="form-control" name="nomFabri" id="nomFabri" value="{{$form_t5->nomFabri}}" maxlength="100">
                    </div>
                </div>
            </div>

              <div class="row">
                  <div class="col-md-12 form-group"><br>
                    <center><button type="submit" class="btn btn-sm btn-info" name="#"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> <b>Modificar</b></button>
                     <a href="{{ url('/histoMarcas') }}"  class="btn btn-sm btn-danger" ><i class="fa fa-reply " aria-hidden="true" title="Regresar"></i> <b>Regresar</b></a></center>  

                  </div>
              </div>
        </div>
    </div>
</div>
</form>
</body>
</html>
    <script src="{{ asset('js/jquery-3.1.0.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/moment.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('js/validate.js') }}"></script>
    <script src="{{ asset('js/jquery.validate.js') }}"></script>
    <script src="{{ asset('js/validateGeneral.js') }}"></script>