routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
}); 
Route::get('/login', function () {
    return view('auth.login');
});


Route::post('/sesion', 'controladorLogin@login');
Route::get('/prueba', 'controladorLogin@prueba');
Route::get('/logout', 'controladorLogin@logout');
/*==============================================*/
/*==============================================*/

#SEGURIDAD DEL MIDDLEWARE PARA LA URL ARCHIVOS QUE LO DOMINAN: /En: MIDDLEWARE SECURITY FOR THE URL DOMAIN FILE: 
#middlewareSesion.php/kernel.php/controladorLogin /En: middlewareSesion.php / kernel.php / controllerLogin

/*=================================================*/
             #RUTAS PARA LOS USUARIOS LOGUEADOS
/*=================================================*/

if(!isset($_SESSION)) 
{ 
    session_start(); 
} 

Route::group(['middleware' => 'sesion'], function () {
	Route::get('/home', 'homeController@index');
});

Route::group(['middleware' => 'analista'], function () {
	Route::get('/proveedores', 'controladorProveedores@index');
	Route::resource('proveedores', 'controladorProveedores');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-provee', 'controladorProveedores@exportProvee');

	# ANEXO T2 = concurso
	Route::get('/concurso', 'controladorConcurso@index');
	Route::resource('concurso', 'controladorConcurso');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-concu', 'controladorConcurso@exportConcurso');

	# ANEXO T2-1 = directa
	Route::get('/directa', 'controladorDirecta@index');
	Route::resource('directa', 'controladorDirecta');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-directa', 'controladorDirecta@exportDirecta');

	# ANEXO T2-2 = confiscacion
	Route::get('/confiscacion', 'controladorConfiscacion@index');
	Route::resource('confiscacion', 'controladorConfiscacion');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-confiscacion', 'controladorConfiscacion@exportConfis');

	# ANEXO T2-3 = dacion
	Route::get('/dacion', 'controladorDacion@index');
	Route::resource('dacion', 'controladorDacion');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-dacion', 'controladorDacion@exportDacion');

	# ANEXO T2-4 = donacion
	Route::get('/donacion', 'controladorDonacion@index');
	Route::resource('donacion', 'controladorDonacion');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-donacion', 'controladorDonacion@exportDonacion');

	# ANEXO T2-5 = expropiacion
	Route::get('/expropiacion', 'controladorExpropiacion@index');
	Route::resource('expropiacion', 'controladorExpropiacion');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-expro', 'controladorExpropiacion@exportExpro');

	# ANEXO T2-6 = permuta
	Route::get('/permuta', 'controladorPermuta@index');
	Route::resource('permuta', 'controladorPermuta');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-permuta', 'controladorPermuta@exportPermuta');

	# ANEXO T2-7 = transferencia
	Route::get('/transferencia', 'controladorTransferencia@index');
	Route::resource('transferencia', 'controladorTransferencia');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-transfe', 'controladorTransferencia@exportTransfe');

	# ANEXO T2-8 = adjudicacion
	Route::get('/adjudicacion', 'controladorAdjudicacion@index');
	Route::resource('adjudicacion', 'controladorAdjudicacion');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-adjud', 'controladorAdjudicacion@exportAdjud');

	# ANEXO T3 = seguros
	Route::get('/seguros', 'controladorSeguros@index');
	Route::resource('seguros', 'controladorSeguros');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-seguro', 'controladorSeguros@exportSeguro');

	# ANEXO T4 = responsables
	Route::get('/responsables', 'controladorResponsables@index');
	Route::resource('responsables', 'controladorResponsables');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-respon', 'controladorResponsables@exportRespon');


	# ANEXO T5 = Marcas
	Route::resource('marcas', 'controladorAddMarca');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-marcas', 'controladorAddMarca@exportMarcas');

	# ANEXO T6 = Modelos
	Route::get('/modelos', 'controladorAddModelos@index');
	Route::resource('modelos', 'controladorAddModelos');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-modelos', 'controladorAddModelos@exportModelos');

	# ANEXO T7 = Componentes
	Route::get('/componentes', 'controladorComponentes@index');
	Route::resource('componentes', 'controladorComponentes');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-compo', 'controladorComponentes@exportCompo');

	# ANEXO T8 = Bienes
	Route::get('/bienes', 'controladorBienes@index');
	Route::resource('bienes', 'controladorBienes');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-bienes', 'controladorBienes@exportBienes');

	# ANEXO T9 = Equipo de Transporte
	Route::get('/transporte', 'controladorEqtransporte@index');
	Route::resource('transporte', 'controladorEqtransporte');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-trans', 'controladorEqtransporte@exportTranspo');

	# ANEXO T10 = Semovientes
	Route::get('/semovientes', 'controladorSemovientes@index');
	Route::resource('semovientes', 'controladorSemovientes');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-semo', 'controladorSemovientes@exportSemo');

	# ANEXO T11 = Datos de los Bienes
	Route::get('/datosbienes', 'controladorDatosbienes@index');
	Route::resource('datosbienes', 'controladorDatosbienes');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-muebles', 'controladorDatosbienes@exportMuebles');

	# ANEXO T12 = Datos de los Inmuebles
	Route::get('/datosinmuebles', 'controladorInmuebles@index');
	Route::resource('datosinmuebles', 'controladorInmuebles');
			/*=========Imprimir Reporte==========*/
	Route::get('/export-inmuebles', 'controladorInmuebles@exportInmuebles');

	# SELECT DINAMICOS
			/*===Registrar Marcas y Modelos Anexos T===*/
	Route::get('dropdown/{id}','controladorBienes@getBienes');

	/*============Modificar Marcas y Modelos Anexos T==============*/
	Route::get('dropdown2/{id}','controladorBienes@getBienesmodif');

			/*===Registrar dependencia y responsable Anexos  T -Bienes===*/
	Route::get('downsede/{id}','controladorBienes@depenResponsable');

	/*============Registrar dependencia y responsable Anexos T -Transporte==============*/
	Route::get('downtran/{id}','controladorEqtransporte@depenResponsable');

	/*============Registrar dependencia y responsable Anexos T -Semovientes==============*/
	Route::get('downsemo/{id}','controladorSemovientes@depenResponsemo');

	/*============Registrar dependencia y responsable Anexos T -Inmuebles==============*/
	Route::get('downinmu/{id}','controladorInmuebles@depenResponsableIn');

	/*=================================================*/
				  # ANEXOS S
				  # ANEXO S1 = Datos Básicos
	/*=================================================*/

	Route::get('/basicos', 'controladorS1@index');
	Route::resource('basicos', 'controladorS1');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-basicos', 'controladorS1@exporBasicos');

	# ANEXO S2 = Datos Máxima Autoridad
	Route::get('/maxima', 'controladorS2@index');
	Route::resource('maxima', 'controladorS2');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-maxima', 'controladorS2@exportMaxima');

	# ANEXO S3 = Datos del Responsable Patrimonial
	Route::get('/patrimonial', 'controladorS3@index');
	Route::resource('patrimonial', 'controladorS3');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-patrimonial', 'controladorS3@exportPatrimonial');

	# ANEXO S4 = Datos de la sede
	Route::get('/sedes', 'controladorS4@index');
	Route::resource('sedes', 'controladorS4');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-sedes', 'controladorS4@exportSedes');

	# ANEXO S5 = Datos de las Unidades Administrativas
	Route::get('/unidades', 'controladorS5@index');
	Route::resource('unidades', 'controladorS5');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-unidades', 'controladorS5@exportUnidades');

	# ANEXO S6 = Datos de las Unidades Administrativas
	Route::get('/ubicacion', 'controladorS6@index');
	Route::resource('ubicacion', 'controladorS6');
	/*=========Imprimir Reporte==========*/
	Route::get('/export-ubicacion', 'controladorS6@exportUbicacion');


	/*------------------------------  // -------------------------*/

	# SELECT LOCALIZACIÓN Y SELECT CODIGO DE PARROQUIA PARA CUANDO SELECCIONE INTERNACIONAL SE COLOQUE 99 EN CASO CONTRARIO TRAIGA LAS OPCIONES DEL OPTION(SELECT)

	/*------------- Vista Inmuebles pertenece al controlador inmuebles-------------*/

	/*== Ruta Paises ==*/
	Route::get('paisIn/{id}', 'controladorInmuebles@paisInmu');
	/*== Ruta Parroquias ==*/
	Route::get('parroIn/{id}', 'controladorInmuebles@parroInmu');
	/*== Ruta Ciudad ==*/
	Route::get('ciudadIn/{id}', 'controladorInmuebles@ciudadInmu');

	/* Modificar Inmuebles pertenece al controlador inmuebles*/
	/*== Ruta Paises ==*/
	Route::get('paisModi/{id}', 'controladorInmuebles@modifiPais');
	/*== Ruta Parroquias ==*/
	Route::get('parroModi/{id}', 'controladorInmuebles@modifiParro');
	/*== Ruta Ciudad ==*/
	Route::get('ciudadModi/{id}', 'controladorInmuebles@modifiCiudad');

	/*------------------------------  // -------------------------*/

	/*------------- Vista Datos de las Sedes pertenece al controladorS4 -------------*/

	/*== Ruta Paises S4 ==*/

resources/views/layouts/ModificarAnexosS/modificarBasicos.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Modificar Básicos</title>

     <link href="{{ asset('css/app.css') }}" rel="stylesheet">
     <link href="{{ asset('css/appstilo.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/general.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/tablas.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
     <link href="{{ asset('css/bootstrap-datepicker.min.css') }}" rel="stylesheet" type="text/css">
     <link href="{{ asset('img/bandera.png') }}" rel="icon">

  </head>
<body>

<div class="container" id="sha">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="panel">
                     <img src="{{URL::asset('/img/cintillo.jpg')}}" id="banner" alt="Cintillo Web">
                   <div class="panel-heading text-center"><h5><b>MODIFICAR BÁSICOS <i class="fa fa-pencil-square-o" aria-hidden="true"></i></b></h5></div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-center">
                    <h4>Modificar Registro <b id="colorInstruccion">N°# {{$form_s1->id}}</b></h4>
                </div>
            </div>
            
          <hr>

            <div class="row">
                <div class="col-md-12 desvanecer">
                  @if(session()->has('msj'))
                      <center><div  class="col-md-12  alert alert-success" role="alert">{{session('msj')}}</div></center>
                         @endif

                         @if(session()->has('errormsj'))
                      <center><div  class="col-md-12  alert alert-danger" role="alert">{{session('errormsj')}}</div></center>
                  @endif
                </div>
            </div>

    <form role="form" id="formValidaS1" name="formValidaS1" method="POST"  action="{{route('basicos.update', $form_s1->id)}}">
        <input type="hidden" name="_method" value="PUT">
           {{ csrf_field() }}

            <div class="row separar">
                <div class="col-md-12">
                    <div class="col-md-4">
                       <label for="codSigecof"><b class="requiredV">*</b>Código SIGECOF</label>
                          <input type="text" class="form-control" name="codSigecof" id="codSigecof" value="{{$form_s1->codSigecof}}"  placeholder="Introduzca nombres" maxlength="30"> 
                    </div>
               
                    <div class="col-md-4">
                       <label for="siglas">Siglas</label> 
                        @if($form_s1->siglas == '1')  
                          <input type="text" class="form-control" name="siglas" id="siglas" value="xxx" maxlength="15"> 
                        @else
                          <input type="text" class="form-control" name="siglas" id="siglas" value="{{$form_s1->siglas}}" maxlength="15">
                        @endif
                    </div>
              
                    <div class="col-md-1 form-group ">
                      <li><b class="requiredV">*</b>RIF</li>
                         <select name="grupo" id="grupo" class="form-control">
                            <option value="1" >J</option>
                            <option value="2" >V</option>
                            <option value="3" >G</option>
                         </select>
                    </div>

                    <div class="col-md-3">
                      <label for="rifProvee">Introduzca el número de RIF</label>   
                       <input type="text" class="form-control" name="rifProvee" id="rifProvee" value="{{$form_s1->rifProvee}}" maxlength="20"> 
                    </div>
                </div>
            </div>
<!--FIN DEL PRIMER ROW DE INPUT-->
            <div class="row separar col-md-offset-1">
                <div class="col-md-12">
                    <div class="col-md-10 form-estilo">
                      <label>Razón Social:</label>
                        @if($form_s1->razonSocial == '1')
                        <textarea name="razonSocial" id="razonSocial" value="xxx" class="form-control" maxlength="255" rows="4">xxx</textarea>
                        <div id="negro" for="contador">Caracteres: <div class="rojo" id="basicos">0/255</div> </div>
                                 
                        @else
                        <textarea name="razonSocial" id="razonSocial" class="form-control" maxlength="255" rows="4">{{$form_s1->razonSocial}}</textarea>
                        <div id="negro" for="contador">Caracteres: <div class="rojo" id="basicos">0/255</div> </div>
                        @endif
                    </div>
                </div>
            </div>
            
            <div class="row separar">
                <div class="col-md-12">    
                    <div class="col-md-4">
                       <label for="telfEnte"><b class="requiredV">*</b>Teléfono</label> 
                        @if($form_s1->telfEnte == '0')  
                          <input type="text" class="form-control" name="telfEnte" id="telfEnte" value="xxx" maxlength="10"> 
                        @else
                          <input type="text" class="form-control" name="telfEnte" id="telfEnte" value="{{$form_s1->telfEnte}}" maxlength="10" onkeypress="return soloNum(event)">
                        @endif
                    </div>

                    <div class="col-md-4">
                       <label for="telfEnte"><b class="requiredV">*</b>Dirección Web</label> 
                        @if($form_s1->direcWeb == '1')  
                          <input type="text" class="form-control" name="direcWeb" id="direcWeb" value="xxx" maxlength="100"> 
                        @else
                          <input type="text" class="form-control" name="direcWeb" id="direcWeb" value="{{$form_s1->direcWeb}}" maxlength="100">
                        @endif
                    </div>

                    <div class="col-md-4">
                       <label for="telfEnte"><b class="requiredV">*</b>Correo Electrónico</label> 
                        @if($form_s1->correEnte == '1')  
                          <input type="text" class="form-control" name="correEnte" id="correEnte" value="xxx" maxlength="100"> 
                        @else
                          <input type="text" class="form-control" name="correEnte" id="correEnte" value="{{$form_s1->correEnte}}" maxlength="100">
                        @endif
                    </div>
                </div> 
            </div>
<!--FIN DEL SEGUNDO ROW DE INPUT-->
            <div class="row separar">
                <div class="col-md-12">
                    <div class="col-md-4">
                       <label for="telfEnte">Fecha Gaceta</label> 
                        @if($form_s1->feGaceta == '1111-11-11')  
                          <input type="text" class="form-control calendario" name="feGaceta" id="feGaceta" value="11111111" maxlength="10"> 
                        @else
                          <input type="text" class="form-control calendario" name="feGaceta" id="feGaceta" value="{{$form_s1->feGaceta}}" maxlength="10">
                        @endif
                    </div>

                    <div class="col-md-4">
                       <label for="telfEnte">Número de Gaceta</label> 
                        @if($form_s1->numGaceta == '1')  
                          <input type="text" class="form-control" name="numGaceta" id="numGaceta" value="xxx" maxlength="10"> 
                        @else
                          <input type="text" class="form-control" name="numGaceta" id="numGaceta" value="{{$form_s1->numGaceta}}" maxlength="10">
                        @endif
                    </div>
                </div>
            </div>
              <div class="row">
                  <div class="col-md-12 form-group"><br>
                    <center><button type="submit" class="btn btn-sm btn-info" name="#"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> <b>Modificar</b></button>
                     <a href="{{ url('/regBasicos') }}"  class="btn btn-sm btn-danger" ><i class="fa fa-reply " aria-hidden="true" title="Regresar"></i> <b>Regresar</b></a></center>  
                  </div>
              </div>
        </div>
    </div>
</div>
</form>
</body>
</html>

    <script src="{{ asset('js/jquery-3.1.0.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/moment.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('js/validate.js') }}"></script>
    <script src="{{ asset('js/validateGeneral.js') }}"></script>
    <script src="{{ asset('js/dropdown.js') }}"></script>
    <script src="{{ asset('js/inputDinamicoanexosT.js') }}"></script>
    <script src="{{ asset('js/contadorTextarea.js') }}"></script>
    <script src="{{ asset('js/selectBuscador.js') }}"></script>
    <script src="{{ asset('js/jquery.validate.js') }}"></script>
    <script src="{{ asset('js/validateDatepicker.js') }}"></script>

resources/views/layouts/ModificarAnexosS/modificarMaxima.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Modificar Máxima</title>

     <link href="{{ asset('css/app.css') }}" rel="stylesheet">
     <link href="{{ asset('css/appstilo.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/general.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/tablas.css') }}" rel="stylesheet">  
     <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
     <link href="{{ asset('css/bootstrap-datepicker.min.css') }}" rel="stylesheet" type="text/css">
     <link href="{{ asset('img/bandera.png') }}" rel="icon">

  </head>
<body>

<div class="container" id="sha">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="panel">
                     <img src="{{URL::asset('/img/cintillo.jpg')}}" id="banner" alt="Cintillo Web">
                   <div class="panel-heading text-center"><h5><b>MODIFICAR DATOS DE LA MÁXIMA AUTORIDAD DEL ÓRGANO O ENTE <i class="fa fa-pencil-square-o" aria-hidden="true"></i></b></h5></div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-center">
                    <h4>Modificar Registro <b id="colorInstruccion">N°# {{$form_s2->id}}</b></h4>
                </div>
            </div>
            
          <hr>

            <div class="row">
                <div class="col-md-12 desvanecer">
                  @if(session()->has('msj'))
                      <center><div  class="col-md-12  alert alert-success" role="alert">{{session('msj')}}</div></center>
                         @endif

                         @if(session()->has('errormsj'))
                      <center><div  class="col-md-12  alert alert-danger" role="alert">{{session('errormsj')}}</div></center>
                  @endif
                </div>
            </div>

    <form role="form" method="POST"  id="formValidaS2" name="formValidaS2" action="{{route('maxima.update', $form_s2->id)}}">
        <input type="hidden" name="_method" value="PUT">
           {{ csrf_field() }}

            <div class="row separar">
                <div class="col-md-12">
                    <div class="col-md-4">
                       <label for="cedula"><b class="requiredV">*</b>Cédula</label>
                       @if($form_s2->cedula == '1')
                          <input type="text" class="form-control" name="cedula" id="cedula" value="xxx"  placeholder="Introduzca el número de cédula" maxlength="8"> 
                       @else
                          <input type="text" class="form-control" name="cedula" id="cedula" value="{{$form_s2->cedula}}"  placeholder="Introduzca el número de cédula" maxlength="8"> 
                       @endif
                    </div>
               
                    <div class="col-md-4">
                       <label for="nombre"><b class="requiredV">*</b>Nombre</label> 
                        @if($form_s2->nombre == '1')  
                          <input type="text" class="form-control" name="nombre" id="nombre" value="xxx" maxlength="100"> 
                        @else
                          <input type="text" class="form-control" name="nombre" id="nombre" value="{{$form_s2->nombre}}" maxlength="100">
                        @endif
                    </div>
                    
                    <div class="col-md-4">
                       <label for="nombre"><b class="requiredV">*</b>Apellido</label> 
                        @if($form_s2->apellido == '1')  
                          <input type="text" class="form-control" name="apellido" id="apellido" value="xxx" maxlength="100"> 
                        @else
                          <input type="text" class="form-control" name="apellido" id="apellido" value="{{$form_s2->apellido}}" maxlength="100">
                        @endif
                    </div>
                </div>
            </div>
<!--FIN DEL PRIMER ROW DE INPUT-->
            <div class="row separar">
                <div class="col-md-12">
                    <div class="col-md-4">
                       <label for="nombre"><b class="requiredV">*</b>Teléfono</label> 
                        @if($form_s2->telefono == '0')  
                          <input type="text" class="form-control" name="telefono" id="telefono" value="xxx" maxlength="10"> 
                        @else
                          <input type="text" class="form-control" name="telefono" id="telefono" value="{{$form_s2->telefono}}" maxlength="10">
                        @endif
                    </div>

                    <div class="col-md-4">
                       <label for="nombre"><b class="requiredV">*</b>Cargo</label> 
                        @if($form_s2->cargo == '1')  
                          <input type="text" class="form-control" name="cargo" id="cargo" value="xxx" maxlength="100"> 
                        @else
                          <input type="text" class="form-control" name="cargo" id="cargo" value="{{$form_s2->cargo}}" maxlength="100">
                        @endif
                    </div>

                    <div class="col-md-4">
                       <label for="nombre"><b class="requiredV">*</b>Correo Electrónico</label> 
                        @if($form_s2->correo == '1')  
                          <input type="text" class="form-control" name="correo" id="correo" value="xxx" maxlength="100"> 
                        @else
                          <input type="text" class="form-control" name="correo" id="correo" value="{{$form_s2->correo}}" maxlength="100">
                        @endif
                    </div>
                </div>
            </div>
            
            <div class="row separar">
                <div class="col-md-12">    
                    <div class="col-md-4">
                       <label for="numGaceta">Número de Gaceta</label> 
                        @if($form_s2->numGaceta == '0')  
                          <input type="text" class="form-control" name="numGaceta" id="numGaceta" value="xxx" maxlength="10"> 
                        @else
                          <input type="text" class="form-control" name="numGaceta" id="numGaceta" value="{{$form_s2->numGaceta}}" maxlength="10" onkeypress="return soloNum(event)">
                        @endif
                    </div>

                    <div class="col-md-4">
                       <label for="telfEnte">Fecha Gaceta</label> 
                        @if($form_s2->feGaceta == '1111-11-11')  
                          <input type="text" class="form-control calendario" name="feGaceta" id="feGaceta" value="11111111" maxlength="10"> 
                        @else
                          <input type="text" class="form-control calendario" name="feGaceta" id="feGaceta" value="{{$form_s2->feGaceta}}" maxlength="10">
                        @endif
                    </div>

                    <div class="col-md-4">
                       <label for="numDecre">Número de Resolución ó Decreto</label> 
                        @if($form_s2->numDecre == '0')  
                          <input type="text" class="form-control" name="numDecre" id="numDecre" value="xxx" maxlength="10"> 
                        @else
                          <input type="text" class="form-control" name="numDecre" id="numDecre" value="{{$form_s2->numDecre}}" maxlength="10" onkeypress="return soloNum(event)">
                        @endif
                    </div>
                </div> 
            </div>
<!--FIN DEL SEGUNDO ROW DE INPUT-->
            <div class="row separar">
                <div class="col-md-12">
                    <div class="col-md-4">
                       <label for="telfEnte">"Fecha de Resolución ó Decreto</label> 
                        @if($form_s2->feDecre == '1111-11-11')  
                          <input type="text" class="form-control calendario" name="feDecre" id="feDecre" value="11111111" maxlength="10"> 
                        @else
                          <input type="text" class="form-control calendario" name="feDecre" id="feDecre" value="{{$form_s2->feDecre}}" maxlength="10">
                        @endif
                    </div>
                </div>
            </div>
              <div class="row">
                  <div class="col-md-12 form-group"><br>
                    <center><button type="submit" class="btn btn-sm btn-info" name="#"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> <b>Modificar</b></button>
                     <a href="{{ url('/regMaxima') }}"  class="btn btn-sm btn-danger" ><i class="fa fa-reply " aria-hidden="true" title="Regresar"></i> <b>Regresar</b></a></center>  
                  </div>
              </div>
        </div>
    </div>
</div>
</form>
</body>
</html>

    <script src="{{ asset('js/jquery-3.1.0.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/moment.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('js/validate.js') }}"></script>
    <script src="{{ asset('js/jquery.validate.js') }}"></script>
    <script src="{{ asset('js/validateGeneral.js') }}"></script> 
    <script src="{{ asset('js/dropdown.js') }}"></script>
    <script src="{{ asset('js/inputDinamicobienes.js') }}"></script>
    <script src="{{ asset('js/jquery.mask.min.js') }}"></script>
    <script src="{{ asset('js/funcion.mask.decimal.js') }}"></script>
    <script src="{{ asset('js/contadorTextarea.js') }}"></script>